# Generated by Django 4.1.7 on 2023-02-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.CharField(max_length=6, verbose_name='reserva')),
                ('plate', models.CharField(max_length=8, verbose_name='placa')),
                ('entry_time', models.DateField(auto_now_add=True, verbose_name='horário de entrada')),
                ('departure_time', models.DateField(blank=True, null=True, verbose_name='horário de saída')),
                ('period', models.DurationField(blank=True, null=True, verbose_name='período permanecido em minutos')),
                ('paid', models.BooleanField(default=False, verbose_name='pagamento')),
                ('left', models.BooleanField(default=False, verbose_name='saida')),
            ],
            options={
                'verbose_name': 'historic',
                'verbose_name_plural': 'Historics',
            },
        ),
    ]
